/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteRouteImport } from './routes/app.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEventIndexRouteImport } from './routes/app.event.index'
import { Route as AppDashboardIndexRouteImport } from './routes/app.dashboard.index'
import { Route as AppDashboardUserRouteImport } from './routes/app.dashboard.user'
import { Route as AppDashboardOverviewRouteImport } from './routes/app.dashboard.overview'
import { Route as AppAdminUserRouteImport } from './routes/app.admin.user'
import { Route as AppAdminTenantUserRouteImport } from './routes/app.admin.tenant-user'
import { Route as AppAdminTenantRouteImport } from './routes/app.admin.tenant'
import { Route as AppAdminSchedulesRouteImport } from './routes/app.admin.schedules'
import { Route as AppAdminCategoriesRouteImport } from './routes/app.admin.categories'
import { Route as AppSettingUserIndexRouteImport } from './routes/app.setting.user.index'
import { Route as AppSettingAppIndexRouteImport } from './routes/app.setting.app.index'
import { Route as AppLocalizationTranslateIndexRouteImport } from './routes/app.localization.translate.index'
import { Route as AppEventSchedulesIndexRouteImport } from './routes/app.event.schedules.index'
import { Route as AppEventCategoriesIndexRouteImport } from './routes/app.event.categories.index'
import { Route as AppEventBookingIndexRouteImport } from './routes/app.event.booking.index'
import { Route as AppContentSocialIndexRouteImport } from './routes/app.content.social.index'
import { Route as AppContentHeroIndexRouteImport } from './routes/app.content.hero.index'
import { Route as AppContentGalleryIndexRouteImport } from './routes/app.content.gallery.index'
import { Route as AppContentArticlesIndexRouteImport } from './routes/app.content.articles.index'
import { Route as AppEventCategoriesNewRouteImport } from './routes/app.event.categories.new'
import { Route as AppContentArticleNewRouteImport } from './routes/app.content.article.new'
import { Route as AppEventCategoriesUpdateCatIdRouteImport } from './routes/app.event.categories.update.$catId'
import { Route as AppContentArticleUpdateArIdRouteImport } from './routes/app.content.article.update.$arId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventIndexRoute = AppEventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardUserRoute = AppDashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardOverviewRoute = AppDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUserRoute = AppAdminUserRouteImport.update({
  id: '/admin/user',
  path: '/admin/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminTenantUserRoute = AppAdminTenantUserRouteImport.update({
  id: '/admin/tenant-user',
  path: '/admin/tenant-user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminTenantRoute = AppAdminTenantRouteImport.update({
  id: '/admin/tenant',
  path: '/admin/tenant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSchedulesRoute = AppAdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminCategoriesRoute = AppAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingUserIndexRoute = AppSettingUserIndexRouteImport.update({
  id: '/setting/user/',
  path: '/setting/user/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingAppIndexRoute = AppSettingAppIndexRouteImport.update({
  id: '/setting/app/',
  path: '/setting/app/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocalizationTranslateIndexRoute =
  AppLocalizationTranslateIndexRouteImport.update({
    id: '/localization/translate/',
    path: '/localization/translate/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEventSchedulesIndexRoute = AppEventSchedulesIndexRouteImport.update({
  id: '/event/schedules/',
  path: '/event/schedules/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventCategoriesIndexRoute = AppEventCategoriesIndexRouteImport.update({
  id: '/event/categories/',
  path: '/event/categories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventBookingIndexRoute = AppEventBookingIndexRouteImport.update({
  id: '/event/booking/',
  path: '/event/booking/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentSocialIndexRoute = AppContentSocialIndexRouteImport.update({
  id: '/content/social/',
  path: '/content/social/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentHeroIndexRoute = AppContentHeroIndexRouteImport.update({
  id: '/content/hero/',
  path: '/content/hero/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentGalleryIndexRoute = AppContentGalleryIndexRouteImport.update({
  id: '/content/gallery/',
  path: '/content/gallery/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentArticlesIndexRoute = AppContentArticlesIndexRouteImport.update({
  id: '/content/articles/',
  path: '/content/articles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventCategoriesNewRoute = AppEventCategoriesNewRouteImport.update({
  id: '/event/categories/new',
  path: '/event/categories/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentArticleNewRoute = AppContentArticleNewRouteImport.update({
  id: '/content/article/new',
  path: '/content/article/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventCategoriesUpdateCatIdRoute =
  AppEventCategoriesUpdateCatIdRouteImport.update({
    id: '/event/categories/update/$catId',
    path: '/event/categories/update/$catId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContentArticleUpdateArIdRoute =
  AppContentArticleUpdateArIdRouteImport.update({
    id: '/content/article/update/$arId',
    path: '/content/article/update/$arId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event': typeof AppEventIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles': typeof AppContentArticlesIndexRoute
  '/app/content/gallery': typeof AppContentGalleryIndexRoute
  '/app/content/hero': typeof AppContentHeroIndexRoute
  '/app/content/social': typeof AppContentSocialIndexRoute
  '/app/event/booking': typeof AppEventBookingIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app': typeof AppSettingAppIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event': typeof AppEventIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles': typeof AppContentArticlesIndexRoute
  '/app/content/gallery': typeof AppContentGalleryIndexRoute
  '/app/content/hero': typeof AppContentHeroIndexRoute
  '/app/content/social': typeof AppContentSocialIndexRoute
  '/app/event/booking': typeof AppEventBookingIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app': typeof AppSettingAppIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/event/': typeof AppEventIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles/': typeof AppContentArticlesIndexRoute
  '/app/content/gallery/': typeof AppContentGalleryIndexRoute
  '/app/content/hero/': typeof AppContentHeroIndexRoute
  '/app/content/social/': typeof AppContentSocialIndexRoute
  '/app/event/booking/': typeof AppEventBookingIndexRoute
  '/app/event/categories/': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules/': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate/': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app/': typeof AppSettingAppIndexRoute
  '/app/setting/user/': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/register'
    | '/app/'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard'
    | '/app/event'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles'
    | '/app/content/gallery'
    | '/app/content/hero'
    | '/app/content/social'
    | '/app/event/booking'
    | '/app/event/categories'
    | '/app/event/schedules'
    | '/app/localization/translate'
    | '/app/setting/app'
    | '/app/setting/user'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/app'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard'
    | '/app/event'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles'
    | '/app/content/gallery'
    | '/app/content/hero'
    | '/app/content/social'
    | '/app/event/booking'
    | '/app/event/categories'
    | '/app/event/schedules'
    | '/app/localization/translate'
    | '/app/setting/app'
    | '/app/setting/user'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/register'
    | '/app/'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard/'
    | '/app/event/'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles/'
    | '/app/content/gallery/'
    | '/app/content/hero/'
    | '/app/content/social/'
    | '/app/event/booking/'
    | '/app/event/categories/'
    | '/app/event/schedules/'
    | '/app/localization/translate/'
    | '/app/setting/app/'
    | '/app/setting/user/'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/': {
      id: '/app/event/'
      path: '/event'
      fullPath: '/app/event'
      preLoaderRoute: typeof AppEventIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/user': {
      id: '/app/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/app/dashboard/user'
      preLoaderRoute: typeof AppDashboardUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/overview': {
      id: '/app/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/app/dashboard/overview'
      preLoaderRoute: typeof AppDashboardOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/user': {
      id: '/app/admin/user'
      path: '/admin/user'
      fullPath: '/app/admin/user'
      preLoaderRoute: typeof AppAdminUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/tenant-user': {
      id: '/app/admin/tenant-user'
      path: '/admin/tenant-user'
      fullPath: '/app/admin/tenant-user'
      preLoaderRoute: typeof AppAdminTenantUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/tenant': {
      id: '/app/admin/tenant'
      path: '/admin/tenant'
      fullPath: '/app/admin/tenant'
      preLoaderRoute: typeof AppAdminTenantRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/schedules': {
      id: '/app/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/app/admin/schedules'
      preLoaderRoute: typeof AppAdminSchedulesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/categories': {
      id: '/app/admin/categories'
      path: '/admin/categories'
      fullPath: '/app/admin/categories'
      preLoaderRoute: typeof AppAdminCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setting/user/': {
      id: '/app/setting/user/'
      path: '/setting/user'
      fullPath: '/app/setting/user'
      preLoaderRoute: typeof AppSettingUserIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setting/app/': {
      id: '/app/setting/app/'
      path: '/setting/app'
      fullPath: '/app/setting/app'
      preLoaderRoute: typeof AppSettingAppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/localization/translate/': {
      id: '/app/localization/translate/'
      path: '/localization/translate'
      fullPath: '/app/localization/translate'
      preLoaderRoute: typeof AppLocalizationTranslateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/schedules/': {
      id: '/app/event/schedules/'
      path: '/event/schedules'
      fullPath: '/app/event/schedules'
      preLoaderRoute: typeof AppEventSchedulesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/categories/': {
      id: '/app/event/categories/'
      path: '/event/categories'
      fullPath: '/app/event/categories'
      preLoaderRoute: typeof AppEventCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/booking/': {
      id: '/app/event/booking/'
      path: '/event/booking'
      fullPath: '/app/event/booking'
      preLoaderRoute: typeof AppEventBookingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/social/': {
      id: '/app/content/social/'
      path: '/content/social'
      fullPath: '/app/content/social'
      preLoaderRoute: typeof AppContentSocialIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/hero/': {
      id: '/app/content/hero/'
      path: '/content/hero'
      fullPath: '/app/content/hero'
      preLoaderRoute: typeof AppContentHeroIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/gallery/': {
      id: '/app/content/gallery/'
      path: '/content/gallery'
      fullPath: '/app/content/gallery'
      preLoaderRoute: typeof AppContentGalleryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/articles/': {
      id: '/app/content/articles/'
      path: '/content/articles'
      fullPath: '/app/content/articles'
      preLoaderRoute: typeof AppContentArticlesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/categories/new': {
      id: '/app/event/categories/new'
      path: '/event/categories/new'
      fullPath: '/app/event/categories/new'
      preLoaderRoute: typeof AppEventCategoriesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/article/new': {
      id: '/app/content/article/new'
      path: '/content/article/new'
      fullPath: '/app/content/article/new'
      preLoaderRoute: typeof AppContentArticleNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/categories/update/$catId': {
      id: '/app/event/categories/update/$catId'
      path: '/event/categories/update/$catId'
      fullPath: '/app/event/categories/update/$catId'
      preLoaderRoute: typeof AppEventCategoriesUpdateCatIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/article/update/$arId': {
      id: '/app/content/article/update/$arId'
      path: '/content/article/update/$arId'
      fullPath: '/app/content/article/update/$arId'
      preLoaderRoute: typeof AppContentArticleUpdateArIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCategoriesRoute: typeof AppAdminCategoriesRoute
  AppAdminSchedulesRoute: typeof AppAdminSchedulesRoute
  AppAdminTenantRoute: typeof AppAdminTenantRoute
  AppAdminTenantUserRoute: typeof AppAdminTenantUserRoute
  AppAdminUserRoute: typeof AppAdminUserRoute
  AppDashboardOverviewRoute: typeof AppDashboardOverviewRoute
  AppDashboardUserRoute: typeof AppDashboardUserRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEventIndexRoute: typeof AppEventIndexRoute
  AppContentArticleNewRoute: typeof AppContentArticleNewRoute
  AppEventCategoriesNewRoute: typeof AppEventCategoriesNewRoute
  AppContentArticlesIndexRoute: typeof AppContentArticlesIndexRoute
  AppContentGalleryIndexRoute: typeof AppContentGalleryIndexRoute
  AppContentHeroIndexRoute: typeof AppContentHeroIndexRoute
  AppContentSocialIndexRoute: typeof AppContentSocialIndexRoute
  AppEventBookingIndexRoute: typeof AppEventBookingIndexRoute
  AppEventCategoriesIndexRoute: typeof AppEventCategoriesIndexRoute
  AppEventSchedulesIndexRoute: typeof AppEventSchedulesIndexRoute
  AppLocalizationTranslateIndexRoute: typeof AppLocalizationTranslateIndexRoute
  AppSettingAppIndexRoute: typeof AppSettingAppIndexRoute
  AppSettingUserIndexRoute: typeof AppSettingUserIndexRoute
  AppContentArticleUpdateArIdRoute: typeof AppContentArticleUpdateArIdRoute
  AppEventCategoriesUpdateCatIdRoute: typeof AppEventCategoriesUpdateCatIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminCategoriesRoute: AppAdminCategoriesRoute,
  AppAdminSchedulesRoute: AppAdminSchedulesRoute,
  AppAdminTenantRoute: AppAdminTenantRoute,
  AppAdminTenantUserRoute: AppAdminTenantUserRoute,
  AppAdminUserRoute: AppAdminUserRoute,
  AppDashboardOverviewRoute: AppDashboardOverviewRoute,
  AppDashboardUserRoute: AppDashboardUserRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEventIndexRoute: AppEventIndexRoute,
  AppContentArticleNewRoute: AppContentArticleNewRoute,
  AppEventCategoriesNewRoute: AppEventCategoriesNewRoute,
  AppContentArticlesIndexRoute: AppContentArticlesIndexRoute,
  AppContentGalleryIndexRoute: AppContentGalleryIndexRoute,
  AppContentHeroIndexRoute: AppContentHeroIndexRoute,
  AppContentSocialIndexRoute: AppContentSocialIndexRoute,
  AppEventBookingIndexRoute: AppEventBookingIndexRoute,
  AppEventCategoriesIndexRoute: AppEventCategoriesIndexRoute,
  AppEventSchedulesIndexRoute: AppEventSchedulesIndexRoute,
  AppLocalizationTranslateIndexRoute: AppLocalizationTranslateIndexRoute,
  AppSettingAppIndexRoute: AppSettingAppIndexRoute,
  AppSettingUserIndexRoute: AppSettingUserIndexRoute,
  AppContentArticleUpdateArIdRoute: AppContentArticleUpdateArIdRoute,
  AppEventCategoriesUpdateCatIdRoute: AppEventCategoriesUpdateCatIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
