/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteRouteImport } from './routes/app.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEventIndexRouteImport } from './routes/app.event.index'
import { Route as AppDashboardIndexRouteImport } from './routes/app.dashboard.index'
import { Route as AppDashboardUserRouteImport } from './routes/app.dashboard.user'
import { Route as AppDashboardOverviewRouteImport } from './routes/app.dashboard.overview'
import { Route as AppEventCategoriesIndexRouteImport } from './routes/app.event.categories.index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventIndexRoute = AppEventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardUserRoute = AppDashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardOverviewRoute = AppDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventCategoriesIndexRoute = AppEventCategoriesIndexRouteImport.update({
  id: '/event/categories/',
  path: '/event/categories/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event': typeof AppEventIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event': typeof AppEventIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/event/': typeof AppEventIndexRoute
  '/app/event/categories/': typeof AppEventCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/register'
    | '/app/'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard'
    | '/app/event'
    | '/app/event/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/app'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard'
    | '/app/event'
    | '/app/event/categories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/register'
    | '/app/'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/dashboard/'
    | '/app/event/'
    | '/app/event/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/': {
      id: '/app/event/'
      path: '/event'
      fullPath: '/app/event'
      preLoaderRoute: typeof AppEventIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/user': {
      id: '/app/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/app/dashboard/user'
      preLoaderRoute: typeof AppDashboardUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/overview': {
      id: '/app/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/app/dashboard/overview'
      preLoaderRoute: typeof AppDashboardOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event/categories/': {
      id: '/app/event/categories/'
      path: '/event/categories'
      fullPath: '/app/event/categories'
      preLoaderRoute: typeof AppEventCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardOverviewRoute: typeof AppDashboardOverviewRoute
  AppDashboardUserRoute: typeof AppDashboardUserRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEventIndexRoute: typeof AppEventIndexRoute
  AppEventCategoriesIndexRoute: typeof AppEventCategoriesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardOverviewRoute: AppDashboardOverviewRoute,
  AppDashboardUserRoute: AppDashboardUserRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEventIndexRoute: AppEventIndexRoute,
  AppEventCategoriesIndexRoute: AppEventCategoriesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
