/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteRouteImport } from './routes/app.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingRouteRouteImport } from './routes/app.setting.route'
import { Route as AppLocalizationRouteRouteImport } from './routes/app.localization.route'
import { Route as AppEventRouteRouteImport } from './routes/app.event.route'
import { Route as AppContentRouteRouteImport } from './routes/app.content.route'
import { Route as AppAdminRouteRouteImport } from './routes/app.admin.route'
import { Route as AppSettingIndexRouteImport } from './routes/app.setting.index'
import { Route as AppLocalizationIndexRouteImport } from './routes/app.localization.index'
import { Route as AppEventIndexRouteImport } from './routes/app.event.index'
import { Route as AppDashboardIndexRouteImport } from './routes/app.dashboard.index'
import { Route as AppContentIndexRouteImport } from './routes/app.content.index'
import { Route as AppSettingCollabRouteImport } from './routes/app.setting.collab'
import { Route as AppDashboardUserRouteImport } from './routes/app.dashboard.user'
import { Route as AppDashboardOverviewRouteImport } from './routes/app.dashboard.overview'
import { Route as AppAdminUserRouteImport } from './routes/app.admin.user'
import { Route as AppAdminTenantUserRouteImport } from './routes/app.admin.tenant-user'
import { Route as AppAdminTenantRouteImport } from './routes/app.admin.tenant'
import { Route as AppAdminSchedulesRouteImport } from './routes/app.admin.schedules'
import { Route as AppAdminCategoriesRouteImport } from './routes/app.admin.categories'
import { Route as AppSettingUserIndexRouteImport } from './routes/app.setting.user.index'
import { Route as AppSettingAppIndexRouteImport } from './routes/app.setting.app.index'
import { Route as AppLocalizationTranslateIndexRouteImport } from './routes/app.localization.translate.index'
import { Route as AppEventSchedulesIndexRouteImport } from './routes/app.event.schedules.index'
import { Route as AppEventCategoriesIndexRouteImport } from './routes/app.event.categories.index'
import { Route as AppEventBookingIndexRouteImport } from './routes/app.event.booking.index'
import { Route as AppContentSocialIndexRouteImport } from './routes/app.content.social.index'
import { Route as AppContentHeroIndexRouteImport } from './routes/app.content.hero.index'
import { Route as AppContentGalleryIndexRouteImport } from './routes/app.content.gallery.index'
import { Route as AppContentArticlesIndexRouteImport } from './routes/app.content.articles.index'
import { Route as AppEventCategoriesNewRouteImport } from './routes/app.event.categories.new'
import { Route as AppContentArticleNewRouteImport } from './routes/app.content.article.new'
import { Route as AppEventCategoriesUpdateCatIdRouteImport } from './routes/app.event.categories.update.$catId'
import { Route as AppContentArticleUpdateArIdRouteImport } from './routes/app.content.article.update.$arId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingRouteRoute = AppSettingRouteRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocalizationRouteRoute = AppLocalizationRouteRouteImport.update({
  id: '/localization',
  path: '/localization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventRouteRoute = AppEventRouteRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentRouteRoute = AppContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingIndexRoute = AppSettingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingRouteRoute,
} as any)
const AppLocalizationIndexRoute = AppLocalizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLocalizationRouteRoute,
} as any)
const AppEventIndexRoute = AppEventIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppSettingCollabRoute = AppSettingCollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => AppSettingRouteRoute,
} as any)
const AppDashboardUserRoute = AppDashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardOverviewRoute = AppDashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUserRoute = AppAdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminTenantUserRoute = AppAdminTenantUserRouteImport.update({
  id: '/tenant-user',
  path: '/tenant-user',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminTenantRoute = AppAdminTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSchedulesRoute = AppAdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminCategoriesRoute = AppAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppSettingUserIndexRoute = AppSettingUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppSettingRouteRoute,
} as any)
const AppSettingAppIndexRoute = AppSettingAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppSettingRouteRoute,
} as any)
const AppLocalizationTranslateIndexRoute =
  AppLocalizationTranslateIndexRouteImport.update({
    id: '/translate/',
    path: '/translate/',
    getParentRoute: () => AppLocalizationRouteRoute,
  } as any)
const AppEventSchedulesIndexRoute = AppEventSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AppEventRouteRoute,
} as any)
const AppEventCategoriesIndexRoute = AppEventCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppEventRouteRoute,
} as any)
const AppEventBookingIndexRoute = AppEventBookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => AppEventRouteRoute,
} as any)
const AppContentSocialIndexRoute = AppContentSocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppContentHeroIndexRoute = AppContentHeroIndexRouteImport.update({
  id: '/hero/',
  path: '/hero/',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppContentGalleryIndexRoute = AppContentGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppContentArticlesIndexRoute = AppContentArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppEventCategoriesNewRoute = AppEventCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AppEventRouteRoute,
} as any)
const AppContentArticleNewRoute = AppContentArticleNewRouteImport.update({
  id: '/article/new',
  path: '/article/new',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppEventCategoriesUpdateCatIdRoute =
  AppEventCategoriesUpdateCatIdRouteImport.update({
    id: '/categories/update/$catId',
    path: '/categories/update/$catId',
    getParentRoute: () => AppEventRouteRoute,
  } as any)
const AppContentArticleUpdateArIdRoute =
  AppContentArticleUpdateArIdRouteImport.update({
    id: '/article/update/$arId',
    path: '/article/update/$arId',
    getParentRoute: () => AppContentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/content': typeof AppContentRouteRouteWithChildren
  '/app/event': typeof AppEventRouteRouteWithChildren
  '/app/localization': typeof AppLocalizationRouteRouteWithChildren
  '/app/setting': typeof AppSettingRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/setting/collab': typeof AppSettingCollabRoute
  '/app/content/': typeof AppContentIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event/': typeof AppEventIndexRoute
  '/app/localization/': typeof AppLocalizationIndexRoute
  '/app/setting/': typeof AppSettingIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles': typeof AppContentArticlesIndexRoute
  '/app/content/gallery': typeof AppContentGalleryIndexRoute
  '/app/content/hero': typeof AppContentHeroIndexRoute
  '/app/content/social': typeof AppContentSocialIndexRoute
  '/app/event/booking': typeof AppEventBookingIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app': typeof AppSettingAppIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/setting/collab': typeof AppSettingCollabRoute
  '/app/content': typeof AppContentIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/event': typeof AppEventIndexRoute
  '/app/localization': typeof AppLocalizationIndexRoute
  '/app/setting': typeof AppSettingIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles': typeof AppContentArticlesIndexRoute
  '/app/content/gallery': typeof AppContentGalleryIndexRoute
  '/app/content/hero': typeof AppContentHeroIndexRoute
  '/app/content/social': typeof AppContentSocialIndexRoute
  '/app/event/booking': typeof AppEventBookingIndexRoute
  '/app/event/categories': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app': typeof AppSettingAppIndexRoute
  '/app/setting/user': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/content': typeof AppContentRouteRouteWithChildren
  '/app/event': typeof AppEventRouteRouteWithChildren
  '/app/localization': typeof AppLocalizationRouteRouteWithChildren
  '/app/setting': typeof AppSettingRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/schedules': typeof AppAdminSchedulesRoute
  '/app/admin/tenant': typeof AppAdminTenantRoute
  '/app/admin/tenant-user': typeof AppAdminTenantUserRoute
  '/app/admin/user': typeof AppAdminUserRoute
  '/app/dashboard/overview': typeof AppDashboardOverviewRoute
  '/app/dashboard/user': typeof AppDashboardUserRoute
  '/app/setting/collab': typeof AppSettingCollabRoute
  '/app/content/': typeof AppContentIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/event/': typeof AppEventIndexRoute
  '/app/localization/': typeof AppLocalizationIndexRoute
  '/app/setting/': typeof AppSettingIndexRoute
  '/app/content/article/new': typeof AppContentArticleNewRoute
  '/app/event/categories/new': typeof AppEventCategoriesNewRoute
  '/app/content/articles/': typeof AppContentArticlesIndexRoute
  '/app/content/gallery/': typeof AppContentGalleryIndexRoute
  '/app/content/hero/': typeof AppContentHeroIndexRoute
  '/app/content/social/': typeof AppContentSocialIndexRoute
  '/app/event/booking/': typeof AppEventBookingIndexRoute
  '/app/event/categories/': typeof AppEventCategoriesIndexRoute
  '/app/event/schedules/': typeof AppEventSchedulesIndexRoute
  '/app/localization/translate/': typeof AppLocalizationTranslateIndexRoute
  '/app/setting/app/': typeof AppSettingAppIndexRoute
  '/app/setting/user/': typeof AppSettingUserIndexRoute
  '/app/content/article/update/$arId': typeof AppContentArticleUpdateArIdRoute
  '/app/event/categories/update/$catId': typeof AppEventCategoriesUpdateCatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/register'
    | '/app/admin'
    | '/app/content'
    | '/app/event'
    | '/app/localization'
    | '/app/setting'
    | '/app/'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/setting/collab'
    | '/app/content/'
    | '/app/dashboard'
    | '/app/event/'
    | '/app/localization/'
    | '/app/setting/'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles'
    | '/app/content/gallery'
    | '/app/content/hero'
    | '/app/content/social'
    | '/app/event/booking'
    | '/app/event/categories'
    | '/app/event/schedules'
    | '/app/localization/translate'
    | '/app/setting/app'
    | '/app/setting/user'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/register'
    | '/app/admin'
    | '/app'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/setting/collab'
    | '/app/content'
    | '/app/dashboard'
    | '/app/event'
    | '/app/localization'
    | '/app/setting'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles'
    | '/app/content/gallery'
    | '/app/content/hero'
    | '/app/content/social'
    | '/app/event/booking'
    | '/app/event/categories'
    | '/app/event/schedules'
    | '/app/localization/translate'
    | '/app/setting/app'
    | '/app/setting/user'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/register'
    | '/app/admin'
    | '/app/content'
    | '/app/event'
    | '/app/localization'
    | '/app/setting'
    | '/app/'
    | '/app/admin/categories'
    | '/app/admin/schedules'
    | '/app/admin/tenant'
    | '/app/admin/tenant-user'
    | '/app/admin/user'
    | '/app/dashboard/overview'
    | '/app/dashboard/user'
    | '/app/setting/collab'
    | '/app/content/'
    | '/app/dashboard/'
    | '/app/event/'
    | '/app/localization/'
    | '/app/setting/'
    | '/app/content/article/new'
    | '/app/event/categories/new'
    | '/app/content/articles/'
    | '/app/content/gallery/'
    | '/app/content/hero/'
    | '/app/content/social/'
    | '/app/event/booking/'
    | '/app/event/categories/'
    | '/app/event/schedules/'
    | '/app/localization/translate/'
    | '/app/setting/app/'
    | '/app/setting/user/'
    | '/app/content/article/update/$arId'
    | '/app/event/categories/update/$catId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setting': {
      id: '/app/setting'
      path: '/setting'
      fullPath: '/app/setting'
      preLoaderRoute: typeof AppSettingRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/localization': {
      id: '/app/localization'
      path: '/localization'
      fullPath: '/app/localization'
      preLoaderRoute: typeof AppLocalizationRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/event': {
      id: '/app/event'
      path: '/event'
      fullPath: '/app/event'
      preLoaderRoute: typeof AppEventRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setting/': {
      id: '/app/setting/'
      path: '/'
      fullPath: '/app/setting/'
      preLoaderRoute: typeof AppSettingIndexRouteImport
      parentRoute: typeof AppSettingRouteRoute
    }
    '/app/localization/': {
      id: '/app/localization/'
      path: '/'
      fullPath: '/app/localization/'
      preLoaderRoute: typeof AppLocalizationIndexRouteImport
      parentRoute: typeof AppLocalizationRouteRoute
    }
    '/app/event/': {
      id: '/app/event/'
      path: '/'
      fullPath: '/app/event/'
      preLoaderRoute: typeof AppEventIndexRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/content/': {
      id: '/app/content/'
      path: '/'
      fullPath: '/app/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/setting/collab': {
      id: '/app/setting/collab'
      path: '/collab'
      fullPath: '/app/setting/collab'
      preLoaderRoute: typeof AppSettingCollabRouteImport
      parentRoute: typeof AppSettingRouteRoute
    }
    '/app/dashboard/user': {
      id: '/app/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/app/dashboard/user'
      preLoaderRoute: typeof AppDashboardUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/overview': {
      id: '/app/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/app/dashboard/overview'
      preLoaderRoute: typeof AppDashboardOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/user': {
      id: '/app/admin/user'
      path: '/user'
      fullPath: '/app/admin/user'
      preLoaderRoute: typeof AppAdminUserRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/tenant-user': {
      id: '/app/admin/tenant-user'
      path: '/tenant-user'
      fullPath: '/app/admin/tenant-user'
      preLoaderRoute: typeof AppAdminTenantUserRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/tenant': {
      id: '/app/admin/tenant'
      path: '/tenant'
      fullPath: '/app/admin/tenant'
      preLoaderRoute: typeof AppAdminTenantRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/schedules': {
      id: '/app/admin/schedules'
      path: '/schedules'
      fullPath: '/app/admin/schedules'
      preLoaderRoute: typeof AppAdminSchedulesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/categories': {
      id: '/app/admin/categories'
      path: '/categories'
      fullPath: '/app/admin/categories'
      preLoaderRoute: typeof AppAdminCategoriesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/setting/user/': {
      id: '/app/setting/user/'
      path: '/user'
      fullPath: '/app/setting/user'
      preLoaderRoute: typeof AppSettingUserIndexRouteImport
      parentRoute: typeof AppSettingRouteRoute
    }
    '/app/setting/app/': {
      id: '/app/setting/app/'
      path: '/app'
      fullPath: '/app/setting/app'
      preLoaderRoute: typeof AppSettingAppIndexRouteImport
      parentRoute: typeof AppSettingRouteRoute
    }
    '/app/localization/translate/': {
      id: '/app/localization/translate/'
      path: '/translate'
      fullPath: '/app/localization/translate'
      preLoaderRoute: typeof AppLocalizationTranslateIndexRouteImport
      parentRoute: typeof AppLocalizationRouteRoute
    }
    '/app/event/schedules/': {
      id: '/app/event/schedules/'
      path: '/schedules'
      fullPath: '/app/event/schedules'
      preLoaderRoute: typeof AppEventSchedulesIndexRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/event/categories/': {
      id: '/app/event/categories/'
      path: '/categories'
      fullPath: '/app/event/categories'
      preLoaderRoute: typeof AppEventCategoriesIndexRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/event/booking/': {
      id: '/app/event/booking/'
      path: '/booking'
      fullPath: '/app/event/booking'
      preLoaderRoute: typeof AppEventBookingIndexRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/content/social/': {
      id: '/app/content/social/'
      path: '/social'
      fullPath: '/app/content/social'
      preLoaderRoute: typeof AppContentSocialIndexRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/content/hero/': {
      id: '/app/content/hero/'
      path: '/hero'
      fullPath: '/app/content/hero'
      preLoaderRoute: typeof AppContentHeroIndexRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/content/gallery/': {
      id: '/app/content/gallery/'
      path: '/gallery'
      fullPath: '/app/content/gallery'
      preLoaderRoute: typeof AppContentGalleryIndexRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/content/articles/': {
      id: '/app/content/articles/'
      path: '/articles'
      fullPath: '/app/content/articles'
      preLoaderRoute: typeof AppContentArticlesIndexRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/event/categories/new': {
      id: '/app/event/categories/new'
      path: '/categories/new'
      fullPath: '/app/event/categories/new'
      preLoaderRoute: typeof AppEventCategoriesNewRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/content/article/new': {
      id: '/app/content/article/new'
      path: '/article/new'
      fullPath: '/app/content/article/new'
      preLoaderRoute: typeof AppContentArticleNewRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/app/event/categories/update/$catId': {
      id: '/app/event/categories/update/$catId'
      path: '/categories/update/$catId'
      fullPath: '/app/event/categories/update/$catId'
      preLoaderRoute: typeof AppEventCategoriesUpdateCatIdRouteImport
      parentRoute: typeof AppEventRouteRoute
    }
    '/app/content/article/update/$arId': {
      id: '/app/content/article/update/$arId'
      path: '/article/update/$arId'
      fullPath: '/app/content/article/update/$arId'
      preLoaderRoute: typeof AppContentArticleUpdateArIdRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminCategoriesRoute: typeof AppAdminCategoriesRoute
  AppAdminSchedulesRoute: typeof AppAdminSchedulesRoute
  AppAdminTenantRoute: typeof AppAdminTenantRoute
  AppAdminTenantUserRoute: typeof AppAdminTenantUserRoute
  AppAdminUserRoute: typeof AppAdminUserRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminCategoriesRoute: AppAdminCategoriesRoute,
  AppAdminSchedulesRoute: AppAdminSchedulesRoute,
  AppAdminTenantRoute: AppAdminTenantRoute,
  AppAdminTenantUserRoute: AppAdminTenantUserRoute,
  AppAdminUserRoute: AppAdminUserRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppContentRouteRouteChildren {
  AppContentIndexRoute: typeof AppContentIndexRoute
  AppContentArticleNewRoute: typeof AppContentArticleNewRoute
  AppContentArticlesIndexRoute: typeof AppContentArticlesIndexRoute
  AppContentGalleryIndexRoute: typeof AppContentGalleryIndexRoute
  AppContentHeroIndexRoute: typeof AppContentHeroIndexRoute
  AppContentSocialIndexRoute: typeof AppContentSocialIndexRoute
  AppContentArticleUpdateArIdRoute: typeof AppContentArticleUpdateArIdRoute
}

const AppContentRouteRouteChildren: AppContentRouteRouteChildren = {
  AppContentIndexRoute: AppContentIndexRoute,
  AppContentArticleNewRoute: AppContentArticleNewRoute,
  AppContentArticlesIndexRoute: AppContentArticlesIndexRoute,
  AppContentGalleryIndexRoute: AppContentGalleryIndexRoute,
  AppContentHeroIndexRoute: AppContentHeroIndexRoute,
  AppContentSocialIndexRoute: AppContentSocialIndexRoute,
  AppContentArticleUpdateArIdRoute: AppContentArticleUpdateArIdRoute,
}

const AppContentRouteRouteWithChildren = AppContentRouteRoute._addFileChildren(
  AppContentRouteRouteChildren,
)

interface AppEventRouteRouteChildren {
  AppEventIndexRoute: typeof AppEventIndexRoute
  AppEventCategoriesNewRoute: typeof AppEventCategoriesNewRoute
  AppEventBookingIndexRoute: typeof AppEventBookingIndexRoute
  AppEventCategoriesIndexRoute: typeof AppEventCategoriesIndexRoute
  AppEventSchedulesIndexRoute: typeof AppEventSchedulesIndexRoute
  AppEventCategoriesUpdateCatIdRoute: typeof AppEventCategoriesUpdateCatIdRoute
}

const AppEventRouteRouteChildren: AppEventRouteRouteChildren = {
  AppEventIndexRoute: AppEventIndexRoute,
  AppEventCategoriesNewRoute: AppEventCategoriesNewRoute,
  AppEventBookingIndexRoute: AppEventBookingIndexRoute,
  AppEventCategoriesIndexRoute: AppEventCategoriesIndexRoute,
  AppEventSchedulesIndexRoute: AppEventSchedulesIndexRoute,
  AppEventCategoriesUpdateCatIdRoute: AppEventCategoriesUpdateCatIdRoute,
}

const AppEventRouteRouteWithChildren = AppEventRouteRoute._addFileChildren(
  AppEventRouteRouteChildren,
)

interface AppLocalizationRouteRouteChildren {
  AppLocalizationIndexRoute: typeof AppLocalizationIndexRoute
  AppLocalizationTranslateIndexRoute: typeof AppLocalizationTranslateIndexRoute
}

const AppLocalizationRouteRouteChildren: AppLocalizationRouteRouteChildren = {
  AppLocalizationIndexRoute: AppLocalizationIndexRoute,
  AppLocalizationTranslateIndexRoute: AppLocalizationTranslateIndexRoute,
}

const AppLocalizationRouteRouteWithChildren =
  AppLocalizationRouteRoute._addFileChildren(AppLocalizationRouteRouteChildren)

interface AppSettingRouteRouteChildren {
  AppSettingCollabRoute: typeof AppSettingCollabRoute
  AppSettingIndexRoute: typeof AppSettingIndexRoute
  AppSettingAppIndexRoute: typeof AppSettingAppIndexRoute
  AppSettingUserIndexRoute: typeof AppSettingUserIndexRoute
}

const AppSettingRouteRouteChildren: AppSettingRouteRouteChildren = {
  AppSettingCollabRoute: AppSettingCollabRoute,
  AppSettingIndexRoute: AppSettingIndexRoute,
  AppSettingAppIndexRoute: AppSettingAppIndexRoute,
  AppSettingUserIndexRoute: AppSettingUserIndexRoute,
}

const AppSettingRouteRouteWithChildren = AppSettingRouteRoute._addFileChildren(
  AppSettingRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppContentRouteRoute: typeof AppContentRouteRouteWithChildren
  AppEventRouteRoute: typeof AppEventRouteRouteWithChildren
  AppLocalizationRouteRoute: typeof AppLocalizationRouteRouteWithChildren
  AppSettingRouteRoute: typeof AppSettingRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardOverviewRoute: typeof AppDashboardOverviewRoute
  AppDashboardUserRoute: typeof AppDashboardUserRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppContentRouteRoute: AppContentRouteRouteWithChildren,
  AppEventRouteRoute: AppEventRouteRouteWithChildren,
  AppLocalizationRouteRoute: AppLocalizationRouteRouteWithChildren,
  AppSettingRouteRoute: AppSettingRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDashboardOverviewRoute: AppDashboardOverviewRoute,
  AppDashboardUserRoute: AppDashboardUserRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
